[project]
name = "data-engineering-zoomcamp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lokesh-07", email = "rlokesh.j07@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pandas>=3.0.5",
    "pyarrow>=25.0.1",
]

[project.scripts]
data-engineering-zoomcamp = "data_engineering_zoomcamp:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
